[package]
name = "smol"
version = "0.1.0"
authors = ["CUB3D <callumthom11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.1"
actix-files = "0.2"
actix-identity = "0.2"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
dotenv = "0.15.0"
chrono = "0.4.19"
diesel = { version = "1.4.8", features = ["r2d2", "mysql", "chrono"] }
diesel_migrations = "1.4.0"
log = "0.4.14"
env_logger = "0.9.0"
tracing = { version = "0.1.22", features = ["log"] }
tracing-futures = "0.2.4"
url = "2.2.2"
http = "0.2.5"
askama = "0.10.5"
uuid = { version = "0.8.2", features = ["v4"] }

