[package]
name = "smol"
version = "0.1.0"
authors = ["CUB3D <callumthom11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-files = "0.2"

rand = "0.7"

serde = { version = "1.0", features = ["derive"] }

dotenv = "0.15"

chrono = "0.4"

diesel = { version = "1.4", features = ["r2d2", "mysql", "chrono"] }
diesel_migrations = "1.4"

env_logger = "0.7"

url = "2"
