name: Rust

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-features
# temporarily don't run tests as some require a db
#    - name: Run tests
#      run: cargo test --verbose --all-features
    - name: Run clippy
      run: cargo clippy --all --tests --all-features
    - name: Check formatting
      run: cargo fmt -- --check
